show mod count in list command
bluefireoly/pacmc pull request #64
Opened 2022-07-31 19:42 UTC by btwonion

2022-07-31 21:31 UTC, jakobkmar requested changes
This change results in `getInstalled()` being called twice, which is not necessary. Could you change that please?

2022-07-31 22:21 UTC, btwonion commented
It's fixed now

2022-08-09 12:58 UTC, btwonion commented
Maybe push?

2022-09-10 22:30 UTC, jakobkmar approved these changes

2022-09-10 22:30 UTC, merged